Use runtime directory instead of /tmp for proxied X11 socket

diff --git a/tests/main/interface-desktop/task.yaml b/tests/main/interface-desktop/task.yaml
--- a/tests/main/interface-desktop/task.yaml
+++ b/tests/main/interface-desktop/task.yaml
@@ -69,6 +69,15 @@ execute: |
       [ -f "${XAUTHORITY}" ]
   EOF
 
+  echo "Check that the required mounts are present after restart"
+  workshop_exec stop ws-desktop
+  workshop_exec start ws-desktop
+  workshop_exec exec ws-desktop -- sudo -Hiu workshop /bin/bash -s <<"EOF"
+      set -e
+      [ -S "/tmp/.X11-unix/X${DISPLAY:1}" ]
+      [ -f "${XAUTHORITY}" ]
+  EOF
+
   echo "Disconnect the desktop interface"
   workshop_exec disconnect ws-desktop/test-sdk-desktop:desktop
 
