Attach SDK volumes as read-only

diff --git a/tests/lib/sdk/test-sdk-setup-fail/sdk/hooks/setup-base b/tests/lib/sdk/test-sdk-setup-fail/sdk/hooks/setup-base
--- a/tests/lib/sdk/test-sdk-setup-fail/sdk/hooks/setup-base
+++ b/tests/lib/sdk/test-sdk-setup-fail/sdk/hooks/setup-base
@@ -1,2 +1,8 @@
 #!/usr/bin/bash
-echo "Set up base failed!"; exit 1
+
+if [ -f /home/workshop/setup-base-pass ]; then
+    exit 0
+else
+    echo "Set up base failed!"
+    exit 1
+fi
